<template><div class="page"><ProTable ref="tableRef" :columns="columns" :request-api="getSalaryPage" :dataCallback="dataCallback" row-key="id" title="工资明细" :tool-button="['refresh','setting','search']"><template #tableHeader="scope"><el-button type="primary" :icon="Upload" @click="openCalculate">计算工资</el-button><el-button type="danger" plain :icon="Delete" :disabled="!scope.isSelected" @click="removeMany(scope.selectedListIds)">批量删除</el-button></template><template #operation="scope"><el-button link type="primary" :icon="View" @click="open(scope.row,true)">查看</el-button><el-button link type="primary" :icon="EditPen" @click="open(scope.row,false)">编辑</el-button><el-button link type="primary" :icon="Clock" @click="logRef?.open(scope.row.id)">修改记录</el-button><el-button link type="danger" :icon="Delete" @click="remove(scope.row.id)">删除</el-button></template></ProTable><SalaryDrawer ref="drawerRef"/><SalaryLogDialog ref="logRef"/><ImportExcel ref="importRef"/></div></template>
<script setup lang="ts">
import { reactive,ref } from "vue";import { Clock,Delete,EditPen,Upload,View } from "@element-plus/icons-vue";import { ElMessage,ElMessageBox } from "element-plus";import ProTable from "@/components/ProTable/index.vue";import ImportExcel from "@/components/ImportExcel/index.vue";import type { ColumnProps } from "@/components/ProTable/interface";import type { Salary } from "@/api/interface/hr";import { calculateSalary,deleteSalary,deleteSalaryMany,editSalary,getSalary,getSalaryPage } from "@/api/modules/hr";import SalaryDrawer from "./components/SalaryDrawer.vue";import SalaryLogDialog from "./components/SalaryLogDialog.vue";import { moneyFields } from "./fields";
const tableRef=ref<InstanceType<typeof ProTable>>(),drawerRef=ref<InstanceType<typeof SalaryDrawer>>(),logRef=ref<InstanceType<typeof SalaryLogDialog>>(),importRef=ref<InstanceType<typeof ImportExcel>>();const dataCallback=(d:any)=>({list:d.records,total:d.total});const money=(v:unknown)=>v==null?"":Number(v).toFixed(2);
const columns:ColumnProps[]=reactive([{type:"selection",width:50},{type:"index",label:"序号",width:65},{label:"工资月份",prop:"salaryMonth",width:120,fixed:"left",search:{el:"date-picker",props:{type:"month",valueFormat:"YYYY-MM"}}},{label:"工号",prop:"workNumber",width:90,search:{el:"input-number"}},{label:"姓名",prop:"staffName",width:110,fixed:"left",search:{el:"input"}},{label:"计薪方式",prop:"way",width:100,render:({row}:any)=>row.way===1?"普工":"非普工"},...[["basicNorm","工资基数"],["overNorm","加班基数"],["standardHours","标准工时"],["workHours","上班工时"],["normalHours","正班工时"],["overHours","平时加班"],["weekOverHours","周末加班"],["leaveHours","请假小时"],["nightDays","夜班天数"],["attendanceDeductionHours","考勤扣除小时"]].map(([prop,label])=>({prop,label,width:115})),...moneyFields.map(x=>({prop:x.prop,label:x.label,width:120,render:({row}:any)=>money(row[x.prop])})),{label:"备注",prop:"remark",minWidth:160},{label:"操作",prop:"operation",fixed:"right",width:300}]);
const open=async(row:Salary,isView:boolean)=>drawerRef.value?.acceptParams({row:(await getSalary(row.id)).data,isView,api:editSalary,refresh:tableRef.value?.getTableList});
const calculateAndNotify=async(params:FormData)=>{const result=await calculateSalary(params);const blob=result instanceof Blob?result:new Blob([result],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});if(blob.type.includes("application/json")){const error=JSON.parse(await blob.text());ElMessage.error(error.message||"工资计算失败");throw error;}const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="工资明细.xlsx";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);ElMessage.success("工资计算成功，工资明细已下载");return result;};
const openCalculate=()=>importRef.value?.acceptParams({title:"工资",importApi:calculateAndNotify,getTableList:tableRef.value?.getTableList});
const remove=async(id:number)=>{await ElMessageBox.confirm("确认删除该工资明细吗？","删除确认",{type:"warning"});await deleteSalary(id);ElMessage.success("删除成功");tableRef.value?.getTableList();};
const removeMany=async(ids:number[])=>{await ElMessageBox.confirm(`确认删除选中的 ${ids.length} 条工资明细吗？`,"批量删除确认",{type:"warning"});await deleteSalaryMany(ids);ElMessage.success("批量删除成功");tableRef.value?.clearSelection();tableRef.value?.getTableList();};
</script><style scoped>.page{height:100%;min-height:0}</style>
