<template><el-drawer v-model="visible" :title="`${drawer.isView?'查看':'编辑'}工资明细`" size="720px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="120px"><el-row :gutter="16"><el-col v-for="item in readonlyFields" :key="item.prop" :span="12"><el-form-item :label="item.label"><el-input :model-value="display(item.prop)" disabled /></el-form-item></el-col><el-col v-for="item in moneyFields" :key="item.prop" :span="12"><el-form-item :label="item.label"><el-input-number v-model="form[item.prop]" :disabled="drawer.isView" :precision="2" controls-position="right" style="width:100%" /></el-form-item></el-col><el-col :span="24"><el-form-item label="备注"><el-input v-model="form.remark" :disabled="drawer.isView" type="textarea" /></el-form-item></el-col><el-col v-if="!drawer.isView" :span="24"><el-form-item label="修改原因" prop="changeReason"><el-input v-model="changeReason" type="textarea" :rows="3" /></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="visible=false">关闭</el-button><el-button v-if="!drawer.isView" type="primary" @click="submit">确定</el-button></template></el-drawer></template>
<script setup lang="ts">
import { reactive,ref } from "vue";import { ElMessage,ElMessageBox,type FormInstance } from "element-plus";import type { Salary,SalaryEditRequest } from "@/api/interface/hr";import { moneyFields } from "../fields";
const readonlyFields=[{prop:"salaryMonth",label:"工资月份"},{prop:"workNumber",label:"工号"},{prop:"staffName",label:"姓名"},{prop:"way",label:"计薪方式"},{prop:"basicNorm",label:"工资基数"},{prop:"overNorm",label:"加班基数"},{prop:"standardHours",label:"标准工时"},{prop:"workHours",label:"上班工时"},{prop:"normalHours",label:"正班工时"},{prop:"overHours",label:"平时加班"},{prop:"weekOverHours",label:"周末加班"},{prop:"leaveHours",label:"请假小时"},{prop:"nightDays",label:"夜班天数"},{prop:"attendanceDeductionHours",label:"考勤扣除小时"}] as const;
const visible=ref(false),formRef=ref<FormInstance>(),form=ref<any>({}),original=ref<any>({}),changeReason=ref("");const drawer=reactive({isView:false,api:undefined as any,refresh:undefined as any});
const rules={changeReason:[{validator:(_:any,v:string,done:(e?:Error)=>void)=>v?.trim()?done():done(new Error("请输入修改原因")),trigger:"blur"}]};
const display=(prop:string)=>prop==="way"?(form.value.way===1?"普工":"非普工"):(form.value[prop]??"");
const acceptParams=(params:any)=>{Object.assign(drawer,params);form.value={...params.row};original.value={...params.row};changeReason.value="";visible.value=true;};
const submit=async()=>{if(!(await formRef.value?.validate()))return;const changed=moneyFields.some(x=>x.prop!=="salaryTotal"&&form.value[x.prop]!==original.value[x.prop]);if(changed&&form.value.salaryTotal===original.value.salaryTotal)await ElMessageBox.confirm("后端不会自动重新计算应发工资。当前应发工资未修改，确认继续提交吗？","应发工资确认",{type:"warning"});const body:SalaryEditRequest={id:form.value.id,changeReason:changeReason.value.trim(),remark:form.value.remark};moneyFields.forEach(x=>body[x.prop]=form.value[x.prop]);await drawer.api(body);ElMessage.success("修改工资明细成功");visible.value=false;drawer.refresh?.();};defineExpose({acceptParams});
</script>
