<template>
  <div class="assist-page">
    <div class="view-switch"><el-segmented v-model="viewMode" :options="[{label:'主表',value:'table'},{label:'明细',value:'item'}]" /></div>
    <ProTable :key="viewMode" ref="tableRef" row-key="id" :title="title" :columns="displayColumns" :request-api="requestApi" :data-callback="d=>({list:d.records,total:d.total})" :pagination="true" :tool-button="['refresh','setting','search']" @row-click="handleRowClick">
      <template #tableHeader="scope">
        <el-button type="primary" :icon="CirclePlus" @click="openEditor()">新增{{ title }}</el-button>
        <SelectionSummary v-if="kind!=='requisition'&&viewMode==='item'" :items="selectionSummary" :disabled="!scope.isSelected" @clear="cancelSelect" />
        <el-button v-else-if="kind!=='requisition'" plain :icon="CircleClose" :disabled="!scope.isSelected" @click="cancelSelect">取消选择</el-button>
      </template>
      <template #operation="{row}"><el-button link type="primary" @click="openDetail(row)">查看</el-button><el-button v-if="kind==='requisition'||kind==='purchase'" link type="primary" @click="exportCurrent(row)">导出</el-button><el-button link type="primary" @click="openEditor(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template>
    </ProTable>

    <el-dialog v-model="detailVisible" :title="`${title}明细`" width="88%">
      <el-descriptions v-if="current" :column="3" border class="summary"><el-descriptions-item label="单号">{{ numberOf(current) }}</el-descriptions-item><el-descriptions-item label="日期">{{ dateOf(current) }}</el-descriptions-item><el-descriptions-item label="状态"><PurchaseStatusTag :status="current.status"/></el-descriptions-item></el-descriptions>
      <el-table :data="current?.items||[]" border stripe><el-table-column prop="assistCode" label="辅材编码" min-width="140"/><el-table-column prop="assistName" label="名称" min-width="140"/><el-table-column prop="assistSpec" label="规格" min-width="160"/><el-table-column :prop="qtyField" :label="qtyLabel" min-width="120"/><el-table-column prop="unit" label="单位" width="90"/><el-table-column v-if="kind==='requisition'||kind==='purchase'" label="状态" width="110"><template #default="{row}"><PurchaseStatusTag :status="kind==='purchase'?purchaseItemStatus(row):row.status"/></template></el-table-column><el-table-column v-if="kind==='purchase'" prop="receivedQty" label="回执数量" min-width="120"/><el-table-column prop="remark" label="备注" min-width="160"/></el-table>
    </el-dialog>

    <el-dialog v-model="editorVisible" :title="`${editingId?'编辑':'新增'}${title}`" width="92%" top="4vh" :close-on-click-modal="false">
      <el-form label-width="86px" class="header-form">
        <el-form-item label="日期" required><el-date-picker v-model="form[dateField]" value-format="YYYY-MM-DD"/></el-form-item>
        <el-form-item v-if="kind==='purchase'" label="供应商" required><el-select v-model="form.supId" filterable @change="syncSupplier"><el-option v-for="o in supplierOptions" :key="o.value" :label="o.label" :value="o.value"/></el-select></el-form-item>
        <el-form-item v-if="kind==='receipt'" label="采购单" required><el-select v-model="form.purchaseTableIds" multiple collapse-tags filterable @change="loadPurchases"><el-option v-for="o in purchaseOptions" :key="o.id" :label="o.purchaseNum" :value="o.id"/></el-select></el-form-item>
        <el-form-item label="备注"><el-input v-model.trim="form.remark"/></el-form-item>
      </el-form>
      <div v-if="kind!=='receipt'" class="toolbar"><el-button type="primary" plain @click="form.items.push({})">添加辅材</el-button></div>
      <el-table :data="form.items" border stripe max-height="430">
        <el-table-column v-if="kind==='requisition'" label="辅材" min-width="300"><template #default="{row}"><el-select v-model="row.assistId" filterable @change="selectAssist(row)"><el-option v-for="o in assistOptions" :key="o.id" :label="`${o.code} / ${o.name||''} / ${o.spec||''} / ${assistTypeLabel(o.type)}`" :value="o.id"/></el-select></template></el-table-column>
        <el-table-column v-if="kind==='purchase'" label="未采购材料" min-width="360"><template #default="{row}"><el-select v-model="row.requisitionItemId" filterable @change="selectRequisition(row)"><el-option v-for="o in requisitionOptions" :key="o.id" :label="`${assistTypeLabel(o.assistType)} / ${o.assistCode} / ${o.assistSpec||''} / 未采 ${o.notPurchaseQty} ${o.unit||''}`" :value="o.id"/></el-select></template></el-table-column>
        <el-table-column prop="assistCode" label="辅材编码" min-width="140"/><el-table-column prop="assistName" label="名称" min-width="130"/><el-table-column prop="assistSpec" label="规格" min-width="150"/>
        <el-table-column :label="qtyLabel" min-width="150"><template #default="{row}"><el-input-number v-model="row[qtyField]" :min="1" :step="1" :precision="0" :controls="false"/><span class="unit">{{ row.unit }}</span></template></el-table-column>
        <el-table-column v-if="kind==='purchase'" label="单价" min-width="120"><template #default="{row}"><el-input-number v-model="row.unitPrice" :min="0" :precision="4" :controls="false"/></template></el-table-column>
        <el-table-column label="备注" min-width="140"><template #default="{row}"><el-input v-model.trim="row.remark"/></template></el-table-column>
        <el-table-column label="操作" width="76"><template #default="{$index}"><el-button link type="danger" @click="form.items.splice($index,1)">移除</el-button></template></el-table-column>
      </el-table>
      <template #footer><el-button @click="editorVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">保存</el-button></template>
    </el-dialog>
  </div>
</template>
<script setup lang="ts">
import{computed,h,onMounted,reactive,ref}from"vue";import{ElButton,ElMessage,ElMessageBox}from"element-plus";import{CircleClose,CirclePlus}from"@element-plus/icons-vue";import ProTable from"@/components/ProTable/index.vue";import type{ColumnProps}from"@/components/ProTable/interface";import SelectionSummary from"@/components/SelectionSummary/index.vue";import PurchaseStatusTag from"../components/PurchaseStatusTag.vue";import{deleteDocument,getAssistOptions,getDocument,getSupplierOptions,itemPage,saveDocument,tablePage,unwrap,type AssistKind}from"./service";
const props=defineProps<{kind:AssistKind;title:string}>(),kind=props.kind,tableRef=ref<any>(),viewMode=ref<'table'|'item'>('item'),detailVisible=ref(false),editorVisible=ref(false),saving=ref(false),current=ref<any>(),editingId=ref<number>(),form=reactive<any>({items:[]}),assistOptions=ref<any[]>([]),supplierOptions=ref<any[]>([]),requisitionOptions=ref<any[]>([]),purchaseOptions=ref<any[]>([]);
const selectedList=computed<any[]>(()=>tableRef.value?.selectedList||[]),sumSelected=(field:string)=>selectedList.value.reduce((total,row)=>total+Number(row[field]||0),0),selectionSummary=computed(()=>kind==='receipt'?[{label:'回执数量',value:sumSelected('receiptQty')}]:[{label:'采购数量',value:sumSelected('purchaseQty')},{label:'已回执数量',value:sumSelected('receivedQty')},{label:'待回数量',value:sumSelected('notReceiptQty')}]);
const dateField=computed(()=>kind==='requisition'?'requisitionDate':kind==='purchase'?'purchaseDate':'receiptDate'),qtyField=computed(()=>kind==='requisition'?'requisitionQty':kind==='purchase'?'purchaseQty':'receiptQty'),qtyLabel=computed(()=>kind==='requisition'?'请购数量':kind==='purchase'?'采购数量':'回执数量');
const numberButton=(prop:string,label:string):ColumnProps=>({prop,label,minWidth:160,search:{el:'input'},render:({row}:any)=>h(ElButton,{link:true,type:'primary',onClick:()=>openDetail(row)},()=>row[prop])});const statusColumn={prop:'status',label:'状态',width:110,render:({row}:any)=>h(PurchaseStatusTag,{status:row.status})};
const purchaseItemStatus=(row:any)=>Number(row.notReceiptQty)<=0?'已完成':Number(row.receivedQty)>0?'部分回执':'已采购';
const purchaseItemStatusColumn={prop:'status',label:'状态',width:110,render:({row}:any)=>h(PurchaseStatusTag,{status:purchaseItemStatus(row)})};
const tables:any={requisition:[numberButton('requisitionNum','请购单号'),{prop:'requisitionDate',label:'请购日期',width:120},statusColumn,{prop:'remark',label:'备注',minWidth:140}],purchase:[numberButton('purchaseNum','采购单号'),{prop:'purchaseDate',label:'采购日期',width:120},{prop:'supName',label:'供应商',minWidth:140},{prop:'totalAmount',label:'金额',width:110},statusColumn],receipt:[numberButton('receiptNum','回执单号'),{prop:'receiptDate',label:'回执日期',width:120},{prop:'purchaseNum',label:'采购单号',minWidth:180},{prop:'supName',label:'供应商',minWidth:140},statusColumn]};
const itemColumns=computed<any[]>(()=>[{prop:'assistCode',label:'辅材编码',minWidth:140,search:{el:'input'}},{prop:'assistName',label:'名称',minWidth:140,search:{el:'input'}},{prop:'assistSpec',label:'规格',minWidth:160,search:{el:'input'}},{prop:qtyField.value,label:qtyLabel.value,width:120},{prop:'unit',label:'单位',width:90},...(kind==='requisition'?[statusColumn]:kind==='purchase'?[purchaseItemStatusColumn,{prop:'receivedQty',label:'回执数量',width:120}]:[]),...(kind==='purchase'?[{prop:'remark',label:'备注',minWidth:160,search:{el:'input'}}]:[])]);
const columns=computed<any[]>(()=>[{type:'selection',prop:'id',label:'选择',width:58},{type:'index',prop:'index',label:'序号',width:68},...(viewMode.value==='table'?tables[kind]:itemColumns.value),{prop:'operation',label:'操作',fixed:'right',width:220}]);
const documentColumn={prop:kind==='requisition'?'requisitionNum':kind==='purchase'?'purchaseNum':'receiptNum',label:kind==='requisition'?'请购单号':kind==='purchase'?'采购单号':'回执单号',minWidth:160,search:{el:'input'}};
const tableRemarkColumn={prop:'tableRemark',label:'整单备注',minWidth:180,search:{el:'input'}};
const displayColumns=computed<any[]>(()=>viewMode.value==='table'?columns.value:[...columns.value.slice(0,2),documentColumn,...columns.value.slice(2,-1),tableRemarkColumn,columns.value[columns.value.length-1]]);
const requestApi=(p:any)=>viewMode.value==='table'?tablePage(kind,p):itemPage(kind,p),parentId=(r:any)=>viewMode.value==='table'?r.id:r.tableId,numberOf=(r:any)=>r.requisitionNum||r.purchaseNum||r.receiptNum,dateOf=(r:any)=>r.requisitionDate||r.purchaseDate||r.receiptDate;
const openDetail=async(r:any)=>{current.value=await unwrap(getDocument(kind,parentId(r)));detailVisible.value=true};
const exportCurrent=async(r:any)=>{const id=parentId(r);if(kind==='requisition'){const[{exportRequisitionPdf},document]=await Promise.all([import('../utils/requisitionDocumentPdf'),unwrap<any>(getDocument('requisition',id))]);return exportRequisitionPdf('assist',document)}const[{exportPurchasePdf},document]=await Promise.all([import('../utils/purchaseDocumentPdf'),unwrap<any>(getDocument('purchase',id))]);await exportPurchasePdf('assist',document)};
const reset=()=>{Object.keys(form).forEach(k=>delete form[k]);form.items=[];form[dateField.value]=new Date().toISOString().slice(0,10);editingId.value=undefined};
const loadReqOptions=async(include:number[]=[] )=>{const p:any=await unwrap(itemPage('requisition',{pageNum:1,pageSize:1000})),ids=new Set(include.map(String));requisitionOptions.value=(p.records||[]).filter((i:any)=>Number(i.notPurchaseQty)>0||ids.has(String(i.id)))};
const loadEditorOptions=async(includeIds:number[]=[])=>{if(kind==='requisition')assistOptions.value=await unwrap(getAssistOptions());if(kind==='purchase'){supplierOptions.value=await unwrap(getSupplierOptions());await loadReqOptions(includeIds)}if(kind==='receipt'){const page:any=await unwrap(tablePage('purchase',{pageNum:1,pageSize:1000}));purchaseOptions.value=page.records||[]}};
const openEditor=async(r?:any)=>{reset();let data:any;if(r?.id)data=await unwrap(getDocument(kind,parentId(r)));await loadEditorOptions((data?.items||[]).map((i:any)=>i.requisitionItemId));if(data){editingId.value=data.id;Object.assign(form,JSON.parse(JSON.stringify(data)));if(kind==='receipt')form.purchaseTableIds=[...new Set(form.items.map((i:any)=>i.purchaseTableId).filter(Boolean))]}editorVisible.value=true};
const selectAssist=(row:any)=>{const o=assistOptions.value.find(i=>String(i.id)===String(row.assistId));if(o)Object.assign(row,{assistType:o.type,assistCode:o.code,assistName:o.name,assistSpec:o.spec,unit:o.unit})};
const assistTypeLabel=(type:string)=>({pvc:'PVC',box:'纸箱',nut:'螺母',spacer:'隔片',other:'其他'}[type]||type||'其他');
const selectRequisition=(row:any)=>{const o=requisitionOptions.value.find(i=>String(i.id)===String(row.requisitionItemId));if(o)Object.assign(row,{...o,id:undefined,tableId:undefined,requisitionItemId:o.id,purchaseQty:o.notPurchaseQty,receivedQty:0,notReceiptQty:o.notPurchaseQty})};
const syncSupplier=(id:any)=>{form.supName=supplierOptions.value.find(i=>String(i.value)===String(id))?.label};
const loadPurchases=async(ids:number[])=>{const list=await Promise.all((ids||[]).map(id=>unwrap<any>(getDocument('purchase',id))));form.items=list.flatMap(p=>(p.items||[]).filter((i:any)=>Number(i.notReceiptQty)>0).map((i:any)=>({...i,id:undefined,tableId:undefined,purchaseTableId:p.id,purchaseItemId:i.id,receiptQty:i.notReceiptQty}))) };
const submit=async()=>{if(!form[dateField.value]||!form.items.length)return ElMessage.warning('请填写日期和明细');if(form.items.some((i:any)=>!Number.isInteger(Number(i[qtyField.value]))||Number(i[qtyField.value])<=0))return ElMessage.warning(`${qtyLabel.value}必须是非0正整数`);saving.value=true;try{const data=JSON.parse(JSON.stringify(form));if(editingId.value)data.id=editingId.value;await unwrap(saveDocument(kind,data));ElMessage.success('保存成功');editorVisible.value=false;tableRef.value?.getTableList()}finally{saving.value=false}};
const remove=async(r:any)=>{await ElMessageBox.confirm(`确认删除这张${props.title}吗？`,'删除确认',{type:'warning'});await unwrap(deleteDocument(kind,parentId(r)));ElMessage.success('删除成功');tableRef.value?.getTableList()};
const handleRowClick=(row:any)=>{if(kind!=='requisition')tableRef.value?.element?.toggleRowSelection(row)},cancelSelect=()=>tableRef.value?.element?.clearSelection();
onMounted(async()=>{assistOptions.value=await unwrap(getAssistOptions());if(kind==='purchase')supplierOptions.value=await unwrap(getSupplierOptions());await loadReqOptions();const p:any=await unwrap(tablePage('purchase',{pageNum:1,pageSize:1000}));purchaseOptions.value=p.records||[]});
</script>
<style scoped>.assist-page{padding:0}.view-switch{display:flex;justify-content:flex-end;margin-bottom:12px}.header-form{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:0 12px}.toolbar{margin-bottom:12px}.summary{margin-bottom:16px}.unit{margin-left:8px;color:var(--el-text-color-secondary)}:deep(.el-select){width:100%}:deep(.el-input-number){max-width:120px}@media(max-width:900px){.header-form{grid-template-columns:1fr}}</style>
